
# Site settings

# NB! Set your site's url, otherwise stuff will break :)

url: "http://opacki.me"

# If you're hosting your site at a Project repository on GitHub pages
# (https://yourusername.github.io/repository-name)
# and NOT your user repository (https://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"
#
# NB! Without this *nothing* will work, because it's used in every path :)

# baseurl: /personal-jekyll-theme

# Google tracking id

google-tracking-id: "UA-30113753-1"

# Forces https everywhere in your website, except when you serve it locally
# If you are not hosted on Github Pages, and your host doesn't support https
# then you should disable it

force-https: False

#############
# HTML Head #
#############

lang: "en"
author: "Joseph Opacki"
title: "opacki.me"
description: "Blog and website of Joseph Opacki, blogging mainly for tech, beverage, food, and wonder of the world. Opinions expressed are mine."
keywords: "joseph opacki, opacki, getchester, malware, reverse engineering, computer forensics, python, personal, Code, Program, Hack, Eat, Drink, Travel, Explore, Live"
favicon: "/img/favicon.ico"

################
# Header layout #
################

# black-favicon: "/img/black-lab-glass.ico"
background-img: "../img/intro-bg.jpg"

##############################
# Dynamic Text on the Header #
##############################

dynamic-typing: False
shuffle: True # Shuffle the lines.
loop: True
loop-count: False # Set False for infinite loop, or set any number for finite loop.
type-speed: 10
start-delay: 100
delete-delay: 5000
lines: # You can add HTML Tags in the Text
  - text: "System.Console.WriteLine('Klaatu barada nikto.');"
  - text: "print('I’m sorry, Dave. I’m afraid I can’t do that.')"
  - text: "puts('I’ve seen things you people wouldn’t believe.');"
  - text: "print 'The needs of the many outweigh... the needs of the few...Or the one.'"
  - text: "printf('TEST')"
  - text: "MessageBox(GetActiveWindow(), 'Do... or do not. There is no try.', MB_OK);"
  - text: "MESSAGE('TEST')"
  - text: "NSLog(@'Mom! Dad! It’s evil! Don’t touch it!.');"
  - text: "alert 'Time is an illusion. Lunchtime doubly so.'"
  - text: "System.out.println( 'I must not fear. Fear is the mind-killer. Fear is the little-death that brings total obliteration.' );"

me-img: "/img/me.jpg"

##############################
# Color the browser elements #
##############################
color-browser: "#FFFFFF"
apple-status-bar-style: "white"

################
# Web app mode #
################

web-app-mode: False

# Icons for Web App mode

icon-36p: "/img/web-app/icon-36p.png"
icon-48p: "/img/web-app/icon-48p.png"
icon-72p: "/img/web-app/icon-72p.png"
icon-96p: "/img/web-app/icon-96p.png"
icon-144p: "/img/web-app/icon-144p.png"
icon-192p: "/img/web-app/icon-192p.png"

########
# Blog #
########

enable-gesture-navigation: False

post-preview-words: 200

paginate: 10

email-share: True
fb-share: True
twitter-share: True
linkedin-share: True
reddit-share: True
google-plus-share: True
tumblr-share: False
pinterest-share: False
pocket-share: False
vkontakte-share: False

disqus-shortname: "getchester"

syntax-highlight: True

############
# Timeline #
############

events:
  - image: "/img/timeline/bis.jpg"
    date: "February 8, 2017"
    description: "Phisher Refrain: We Will Crypto-Lock You"
    link: "http://www.bankinfosecurity.com/phisher-refrain-we-will-crypto-lock-you-a-9676"
  - image: "/img/timeline/yahoo.jpg"
    date: "February 7, 2017"
    description: "PhishLabs Releases 2017 Phishing Trends & Intelligence Report, Revealing Profound Shift in Who is Targeted and Why"
    link: "http://finance.yahoo.com/news/phishlabs-releases-2017-phishing-trends-130500535.html"
  - image: "/img/timeline/hsw.png"
    date: "January 6, 2017"
    description: "Why Ransomware Is the Perfect Hack"
    link: "http://now.howstuffworks.com/2017/01/06/why-ransomware-is-perfect-hack"
  - image: "/img/timeline/pc.png"
    date: "December 8, 2016"
    description: "After Mount Pleasant police hit by ransomware attack, experts say take precautions"
    link: "http://www.postandcourier.com/news/after-mount-pleasant-police-hit-by-ransomware-attack-experts-say/article_33c2387e-c249-11e6-b8a0-37e84ee1fd3d.html"
  - image: "/img/timeline/bsides.png"
    date: "November 10, 2016"
    description: "Security BSides Charleston - Keynote"
    link: "https://youtu.be/_647rIK1EbM"
  - image: "/img/timeline/pc.png"
    date: "September 22, 2016"
    description: "Cybersecurity experts: Yahoo hack poses risk beyond initial breach"
    link: "http://www.postandcourier.com/business/cybersecurity-experts-yahoo-hack-poses-risk-beyond-initial-breach/article_84ba0dc5-58b0-5990-975c-785df7087fbc.html"
  - image: "/img/timeline/ftc.jpg"
    date: "September 7, 2016"
    description: "Federal Trade Commission Fall Technology Series: Ransomware"
    link: "https://www.ftc.gov/news-events/audio-video/video/fall-technology-series-ransomware-part-1"
  - image: "/img/timeline/fedscoop.png"
    date: "September 7, 2016"
    description: "FTC chief: Ransomware is the most profitable malware ever devised"
    link: "https://www.fedscoop.com/ftc-chief-ransomware-malware-september-2016/"
  - image: "/img/timeline/prweb.png"
    date: "August 24, 2016"
    description: "PhishLabs VP of Threat Research Joseph Opacki to Speak at Federal Trade Commission Event on Ransomware, Sept. 7 in Washington, D.C."
    link: "http://www.prweb.com/releases/2016/08/prweb13629921.htm"
  - image: "/img/timeline/darkreading.jpg"
    date: "June 21, 2016"
    description: "Phishing, Whaling & The Surprising Importance Of Privileged Users"
    link: "http://www.darkreading.com/endpoint/phishing-whaling-and-the-surprising-importance-of-privileged-users/a/d-id/1325991?utm_content=32196563&utm_medium=social&utm_source=twitter"
  - image: "/img/timeline/instinv.jpg"
    date: "May 13, 2016"
    description: "Banks Urged to Step Up Vigilance in Wake of Bangladesh Hack"
    link: "http://www.institutionalinvestor.com/article/3554362/banking-and-capital-markets-trading-and-technology/banks-urged-to-step-up-vigilance-in-wake-of-bangladesh-hack.html?ArticleId=3554362#/.WJwUc384Tbl"
  - image: "/img/timeline/cw.jpg"
    date: "April 22, 2016"
    description: "The CyberWire Daily Podcast"
    link: "https://thecyberwire.com/podcasts/cw-podcasts-daily-2016-04-22.html"
  - image: "/img/timeline/macworld.gif"
    date: "March 7, 2016"
    description: "PhishLabs on the growing sophistication of business email scams"
    link: "http://www.macworld.com/video/63026/phishlabs-on-the-growing-sophistication-of-business-email-scams"
  - image: "/img/timeline/bis.jpg"
    date: "November 30, 2015"
    description: "Business Email Compromise Attacks Rapidly Evolving"
    link: "http://www.bankinfosecurity.com/interviews/business-email-compromise-attacks-rapidly-evolving-i-3000"
  - image: "/img/timeline/bis.jpg"
    date: "October 26, 2015"
    description: "CISO's Guide to Spear Phishing Defense"
    link: "http://www.bankinfosecurity.com/interviews/cisos-guide-to-spear-phishing-defense-i-2966"
  - image: "/img/timeline/issa.png"
    date: "June 28, 2011"
    description: "The Changing Face of Malware"
    link: "http://www.issa.org/?page=June2011"
  - image: "/img/timeline/scmedia.jpg"
    date: "February 17, 2011"
    description: "RSA Conference 2011: Smartphone threats imminent, security lacking"
    link: "http://www.scmagazine.com/rsa-conference-2011-smartphone-threats-imminent-security-lacking/article/196563/"

# First image of the Timeline

timeline-img: "/img/me.jpg"

###########
# Contact #
###########

email: "joseph@opacki.me"

################
# Author Blurb #
################

# The author blurb goes underneath blog posts.
# This works best when your author blurb image has a transparent background, or matches your site background color.

# if the author_blurb is not set, then this feature is skipped
#author_blurb: "This is brought to you by the letter 'O' and the number eleven!"
#author_blurb_image: "/img/author.png"

##################
# Social Buttons #
##################

social:
  - title: "linkedin"
    url: "https://www.linkedin.com/in/josephopacki"
  - title: "twitter"
    url: "https://twitter.com/josephopacki"
  - title: "github"
    url: "https://github.com/getChester"
  - title: "bitcoin"
    url: "https://blockchain.info/address/1CkGfEEjL19eMcnwKQskKdYEddbWKfrsg1"
  - title: "rss"
    url: "/feed.xml"

############
# 404 page #
############

err-404-img: "/img/me.jpg"

##################
# GPG on Keybase #
##################

keybase-username: getchester
keybase-in-social: True
keybase-in-footer: True

################################################################################

# NB! Tread carefully if you want to change the variables below this point!

# Sections shown in the index page

pages_list:
  About: 'about'
  Blog: 'latest-post'
  Media Mentions: 'timeline'
  Contact: 'contact'

# Exclusion list from the generated _site

exclude: ["LICENSE", "README.md", "CONTRIBUTING", "CONTRIBUTORS", "scripts"]

# Pagination path

paginate_path: "blog/page:num/"

# Enable minification SASS

sass:
  style: compressed

gems:
  - jekyll-paginate
  - jemoji
