
# Site settings

# NB! Set your site's url, otherwise stuff will break :)

url: "https://joseph.opacki.me"

# If you're hosting your site at a Project repository on GitHub pages
# (https://yourusername.github.io/repository-name)
# and NOT your user repository (https://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"
#
# NB! Without this *nothing* will work, because it's used in every path :)

# baseurl: /personal-jekyll-theme

# Google tracking id

google-tracking-id: "UA-30113753-1"

# Forces https everywhere in your website, except when you serve it locally
# If you are not hosted on Github Pages, and your host doesn't support https
# then you should disable it

force-https: True

#############
# HTML Head #
#############

lang: "en"
author: "Joseph Opacki"
title: "opacki.me"
description: "Blog and website of Joseph Opacki, blogging mainly for tech, beverage, food, and wonder of the world. Opinions expressed are mine."
keywords: "joseph opacki, opacki, getchester, malware, reverse engineering, computer forensics, python, personal"
favicon: "/img/favicon.ico"

################
# Header layout #
################

# black-favicon: "/img/black-lab-glass.ico"

background-img: "../img/intro-bg.jpg"

##############################
# Dynamic Text on the Header #
##############################

dynamic-typing: True
shuffle: True # Shuffle the lines.
loop: True
loop-count: False # Set False for infinite loop, or set any number for finite loop.
type-speed: 10
start-delay: 100
delete-delay: 5000
lines: # You can add HTML Tags in the Text
  - text: "System.Console.WriteLine('Code. Program. Hack. Eat. Drink. Travel. Explore. Live.');"
  - text: "print('Code. Program. Hack. Eat. Drink. Travel. Explore. Live.')"
  - text: "puts('Code. Program. Hack. Eat. Drink. Travel. Explore. Live.');"
  - text: "print 'Code. Program. Hack. Eat. Drink. Travel. Explore. Live.'"
  - text: "printf('Code. Program. Hack. Eat. Drink. Travel. Explore. Live.')"
  - text: "MessageBox(GetActiveWindow(), 'Code. Program. Hack. Eat. Drink. Travel. Explore. Live.', MB_OK);"
  - text: "std::cout << 'Code. Program. Hack. Eat. Drink. Travel. Explore. Live.' << std::endl;"
  - text: "MESSAGE('Code. Program. Hack. Eat. Drink. Travel. Explore. Live.')"
  - text: "NSLog(@'Code. Program. Hack. Eat. Drink. Travel. Explore. Live.');"
  - text: "alert 'Code. Program. Hack. Eat. Drink. Travel. Explore. Live.'"
  - text: "<cfoutput>Code. Program. Hack. Eat. Drink. Travel. Explore. Live.</cfoutput>"
  - text: "System.out.println( 'Code. Program. Hack. Eat. Drink. Travel. Explore. Live.' );"
  - text: "<?php echo 'Code. Program. Hack. Eat. Drink. Travel. Explore. Live.'; ?>"
  


me-img: "/img/me.jpg"

##############################
# Color the browser elements #
##############################
color-browser: "#FFFFFF"
apple-status-bar-style: "white"

################
# Web app mode #
################

web-app-mode: False

# Icons for Web App mode

icon-36p: "/img/web-app/icon-36p.png"
icon-48p: "/img/web-app/icon-48p.png"
icon-72p: "/img/web-app/icon-72p.png"
icon-96p: "/img/web-app/icon-96p.png"
icon-144p: "/img/web-app/icon-144p.png"
icon-192p: "/img/web-app/icon-192p.png"

########
# Blog #
########

enable-gesture-navigation: True

post-preview-words: 96

paginate: 5

email-share: True
fb-share: False
twitter-share: True
linkedin-share: True
reddit-share: True
google-plus-share: False
tumblr-share: False
pinterest-share: False
pocket-share: False
vkontakte-share: False

disqus-shortname: "getchester"

syntax-highlight: True

############
# Timeline #
############

events:
  - image: "/img/timeline/spidertocat.png"
    date: "September 2013 - Today"
    description: "Saving the neighborhood!"
    link: "http://joseph.opacki.me"
  - image: "/img/timeline/baracktocat.jpg"
    date: "September 2007 - August 2013"
    description: "Started coding"
    link: "http://joseph.opacki.me"

# First image of the Timeline

timeline-img: "/img/timeline/default.png"

###########
# Contact #
###########

email: "joseph@opacki.me"

################
# Author Blurb #
################

# The author blurb goes underneath blog posts.
# This works best when your author blurb image has a transparent background, or matches your site background color.

# if the author_blurb is not set, then this feature is skipped
author_blurb: "This is brought to you by the letter 'O' and the number eleven!"
#author_blurb_image: "/img/author.png"

##################
# Social Buttons #
##################

social:
  - title: "linkedin"
    url: "https://www.linkedin.com/in/josephopacki"
  - title: "twitter"
    url: "https://twitter.com/josephopacki"
  - title: "github"
    url: "https://github.com/getChester"
  - title: "bitcoin"
    url: "https://blockchain.info/address/1CkGfEEjL19eMcnwKQskKdYEddbWKfrsg1"
  - title: "rss"
    url: "/feed.xml"

############
# 404 page #
############

err-404-img: "/img/labtocat.png"

##################
# GPG on Keybase #
##################

keybase-username: getchester
keybase-in-social: True
keybase-in-footer: True

################################################################################

# NB! Tread carefully if you want to change the variables below this point!

# Sections shown in the index page

pages_list:
  About: 'about'
  Blog: 'latest-post'
  Timeline: 'timeline'
  Contact: 'contact'

# Exclusion list from the generated _site

exclude: ["LICENSE", "README.md", "CONTRIBUTING", "CONTRIBUTORS", "scripts"]

# Pagination path

paginate_path: "blog/page:num/"

# Enable minification SASS

sass:
  style: compressed

gems:
  - jekyll-paginate
  - jemoji
